### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by lisakawai** [UTokyo-SDP/git-ex-02-41#2]
This directory doesn't have any README files. I'm sure it needs.

**Comment by itohdak** [comment]
you can close this issue

**Comment by itohdak** [comment]
I think this issue is resolved with https://github.com/UTokyo-SDP/git-ex-02-41/commit/85a7159709428bf2ccb2cc791990419bc8e6be25.
Could you close?

**Comment by lisakawai** [comment]
Yes.
